const char* urdfstr_2dof =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<robot\n"
        "\tname=\"2dof-arm-assembly-GRAVITY\">\n"
        "\t<link\n"
        "\t\tname=\"base_link\">\n"
        "\t\t<inertial>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"-0.0121676534713795 -0.0876617845542699 -1.133828261053E-18\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<mass\n"
        "\t\t\t\tvalue=\"8.3415926535898\" />\n"
        "\t\t\t<inertia\n"
        "\t\t\t\tixx=\"0.049722770146853\"\n"
        "\t\t\t\tixy=\"-0.00632717980511735\"\n"
        "\t\t\t\tixz=\"-2.88465672099471E-18\"\n"
        "\t\t\t\tiyy=\"0.0654711034101151\"\n"
        "\t\t\t\tiyz=\"-1.15918882856173E-18\"\n"
        "\t\t\t\tizz=\"0.0688192436223524\" />\n"
        "\t\t</inertial>\n"
        "\t\t<visual>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/base_link.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t\t<material\n"
        "\t\t\t\tname=\"\">\n"
        "\t\t\t\t<color\n"
        "\t\t\t\t\trgba=\"0.752941176470588 0.752941176470588 0.752941176470588 1\" />\n"
        "\t\t\t</material>\n"
        "\t\t</visual>\n"
        "\t\t<collision>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/base_link.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t</collision>\n"
        "\t</link>\n"
        "\t<link\n"
        "\t\tname=\"link_1\">\n"
        "\t\t<inertial>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0.35 2.0794E-18 -0.075\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<mass\n"
        "\t\t\t\tvalue=\"25.712\" />\n"
        "\t\t\t<inertia\n"
        "\t\t\t\tixx=\"0.12999\"\n"
        "\t\t\t\tixy=\"-7.0361E-18\"\n"
        "\t\t\t\tixz=\"-1.8745E-17\"\n"
        "\t\t\t\tiyy=\"1.6348\"\n"
        "\t\t\t\tiyz=\"2.8912E-18\"\n"
        "\t\t\t\tizz=\"1.6683\" />\n"
        "\t\t</inertial>\n"
        "\t\t<visual>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/link_1.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t\t<material\n"
        "\t\t\t\tname=\"\">\n"
        "\t\t\t\t<color\n"
        "\t\t\t\t\trgba=\"0.75294 0.75294 0.75294 1\" />\n"
        "\t\t\t</material>\n"
        "\t\t</visual>\n"
        "\t\t<collision>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/link_1.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t</collision>\n"
        "\t</link>\n"
        "\t<joint\n"
        "\t\tname=\"joint_1\"\n"
        "\t\ttype=\"revolute\">\n"
        "\t\t<origin\n"
        "\t\t\txyz=\"-0.032308 -0.36 0\"\n"
        "\t\t\trpy=\"1.5708 0 0\" />\n"
        "\t\t<parent\n"
        "\t\t\tlink=\"base_link\" />\n"
        "\t\t<child\n"
        "\t\t\tlink=\"link_1\" />\n"
        "\t\t<axis\n"
        "\t\t\txyz=\"0 0 1\" />\n"
        "\t\t<limit\n"
        "\t\t\tlower=\"0\"\n"
        "\t\t\tupper=\"0\"\n"
        "\t\t\teffort=\"0\"\n"
        "\t\t\tvelocity=\"0\" />\n"
        "\t</joint>\n"
        "\t<link\n"
        "\t\tname=\"link_2\">\n"
        "\t\t<inertial>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0.30977 -5.9174E-18 -0.071503\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<mass\n"
        "\t\t\t\tvalue=\"23.477\" />\n"
        "\t\t\t<inertia\n"
        "\t\t\t\tixx=\"0.12402\"\n"
        "\t\t\t\tixy=\"1.9103E-17\"\n"
        "\t\t\t\tixz=\"-0.023825\"\n"
        "\t\t\t\tiyy=\"1.2147\"\n"
        "\t\t\t\tiyz=\"1.1803E-17\"\n"
        "\t\t\t\tizz=\"1.2355\" />\n"
        "\t\t</inertial>\n"
        "\t\t<visual>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/link_2.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t\t<material\n"
        "\t\t\t\tname=\"\">\n"
        "\t\t\t\t<color\n"
        "\t\t\t\t\trgba=\"0.75294 0.75294 0.75294 1\" />\n"
        "\t\t\t</material>\n"
        "\t\t</visual>\n"
        "\t\t<collision>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/link_2.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t</collision>\n"
        "\t</link>\n"
        "\t<joint\n"
        "\t\tname=\"joint_2\"\n"
        "\t\ttype=\"revolute\">\n"
        "\t\t<origin\n"
        "\t\t\txyz=\"0.7 0 0.16\"\n"
        "\t\t\trpy=\"0 0 0\" />\n"
        "\t\t<parent\n"
        "\t\t\tlink=\"link_1\" />\n"
        "\t\t<child\n"
        "\t\t\tlink=\"link_2\" />\n"
        "\t\t<axis\n"
        "\t\t\txyz=\"0 0 1\" />\n"
        "\t\t<limit\n"
        "\t\t\tlower=\"0\"\n"
        "\t\t\tupper=\"0\"\n"
        "\t\t\teffort=\"0\"\n"
        "\t\t\tvelocity=\"0\" />\n"
        "\t</joint>\n"
        "\t<link\n"
        "\t\tname=\"end_effector\">\n"
        "\t\t<inertial>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"-0.29023 1.0493E-16 -0.18842\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<mass\n"
        "\t\t\t\tvalue=\"23.477\" />\n"
        "\t\t\t<inertia\n"
        "\t\t\t\tixx=\"0.12402\"\n"
        "\t\t\t\tixy=\"1.9064E-17\"\n"
        "\t\t\t\tixz=\"-0.023825\"\n"
        "\t\t\t\tiyy=\"1.2147\"\n"
        "\t\t\t\tiyz=\"1.2081E-17\"\n"
        "\t\t\t\tizz=\"1.2355\" />\n"
        "\t\t</inertial>\n"
        "\t\t<visual>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/end_effector.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t\t<material\n"
        "\t\t\t\tname=\"\">\n"
        "\t\t\t\t<color\n"
        "\t\t\t\t\trgba=\"0.75294 0.75294 0.75294 1\" />\n"
        "\t\t\t</material>\n"
        "\t\t</visual>\n"
        "\t\t<collision>\n"
        "\t\t\t<origin\n"
        "\t\t\t\txyz=\"0 0 0\"\n"
        "\t\t\t\trpy=\"0 0 0\" />\n"
        "\t\t\t<geometry>\n"
        "\t\t\t\t<mesh\n"
        "\t\t\t\t\tfilename=\"package://2dof-arm-assembly-GRAVITY/meshes/end_effector.STL\" />\n"
        "\t\t\t</geometry>\n"
        "\t\t</collision>\n"
        "\t</link>\n"
        "\t<joint\n"
        "\t\tname=\"end_effector_joint\"\n"
        "\t\ttype=\"fixed\">\n"
        "\t\t<origin\n"
        "\t\t\txyz=\"0.6 0 0.11691\"\n"
        "\t\t\trpy=\"0 0 0\" />\n"
        "\t\t<parent\n"
        "\t\t\tlink=\"link_2\" />\n"
        "\t\t<child\n"
        "\t\t\tlink=\"end_effector\" />\n"
        "\t\t<axis\n"
        "\t\t\txyz=\"0 0 0\" />\n"
        "\t</joint>\n"
        "</robot>\n";