const char* urdfstr_two_segment =
        "<?xml version=\"1.0\">\n"
        "<robot name=\"test\">\n"
        "  <material name=\"Grey\">\n"
        "    <color rgba=\"0.2 0.2 0.2 1.0\"/>"
        "  </material>"
        "  <link name=\"link_0\">\n"
        "    <inertial>\n"
        "      <origin rpy=\"0 0 0\" xyz=\"-0.1 0 0.07\"/>\n"
        "      <mass value=\"5.0\"/>\n"
        "      <inertia ixx=\"0.05\" ixy=\"0\" ixz=\"0\" iyy=\"0.06\" iyz=\"0\" izz=\"0.03\"/>\n"
        "    </inertial>\n"
        "    <visual>\n"
        "      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n"
        "      <geometry>\n"
        "        <mesh filename=\"meshes/link_0.obj\"/>\n"
        "      </geometry>\n"
        "      <material name=\"Grey\"/>\n"
        "    </visual>\n"
        "  </link>\n"
        "<!-- joint between link_0 and link_1 -->\n"
        "  <joint name=\"joint_1\" type=\"revolute\">\n"
        "    <parent link=\"link_0\"/>\n"
        "    <child link=\"link_1\"/>\n"
        "    <origin rpy=\"0 0 0\" xyz=\"0 0 0.1575\"/>\n"
        "    <axis xyz=\"0 0 1\"/>\n"
        "    <limit effort=\"300\" lower=\"-2.96705972839\" upper=\"2.96705972839\" velocity=\"10\"/>\n"
        "    <dynamics damping=\"0.5\"/>\n"
        "  </joint>\n"
        "  <link name=\"link_1\">\n"
        "    <inertial>\n"
        "      <origin rpy=\"0 0 0\" xyz=\"0 -0.03 0.12\"/>\n"
        "      <mass value=\"4\"/>\n"
        "      <inertia ixx=\"0.1\" ixy=\"0\" ixz=\"0\" iyy=\"0.09\" iyz=\"0\" izz=\"0.02\"/>\n"
        "    </inertial>\n"
        "    <visual>\n"
        "      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n"
        "      <geometry>\n"
        "        <mesh filename=\"meshes/link_1.obj\"/>\n"
        "      </geometry>\n"
        "      <material name=\"Blue\"/>\n"
        "    </visual>\n"
        "  </link>\n"
        "</robot>";